project:
  type: website

website:
  title: "Yannick Serge Obam"
  navbar:
    left:
      - href: about.qmd
        text : Home
      - href: projects.qmd
        text : Projects
      - href: talks.qmd
        text : Talks
      - href: index.qmd
        text : Blogs
      - href: resume.qmd
        text : Resume
     
    right:
      - about.qmd
      - icon: github
        href: https://github.com/obeshor
      - icon: twitter
        href: https://twitter.com/OBAMSerge
format:
  html:
    theme: cosmo
    css: styles.css



